version: "3.3"

services:
  web:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000    
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - "8080:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    networks:
      - app-network
      - conexion-network
  
  db:
    image: postgres:15.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - app-network

  suscriber:
    build: ./mqtt-suscriber
    command: python mqtt-client.py
    depends_on:
      - web
    networks:
      - conexion-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
  conexion-network:
    driver: bridge
