name: Test and Lint Workflow

on:
  pull_request:
    branches:
      - main  
      - develop
  push:
    branches:
      - main  
      - develop

jobs:
  linter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        yarn install
  
    - name: Run Lint
      run: |
        yarn lint