version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dev.Dockerfile
    container_name: api
    command: 'npm run server:dev'
    ports:
      - '8080:8080'
      - '9229:9229'
    depends_on:
      - mongodb
    env_file: .env.local
    volumes:
      - './src:/app/src'
      - '/app/node_modules'
    networks:
      - node-network
  
  mongodb:
    image: mongo:4.4.6
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge