from os.path import join

# Rutas
RUTA_JUGADORES = join("datos", "jugadores.csv")
RUTA_JUEGOS = join("datos", "juegos.csv")
RUTA_BEBESTIBLES = join("datos", "bebestibles.csv")


DEUDA_TOTAL = 20000

PROBABILIDAD_EVENTO = 0.8

PORCENTAJE_APUESTA_TACANO = 0.2
BONIFICACION_TACANO = 50

MULTIPLICADOR_BONIFICACION_BEBEDOR = 2
BONIFICACION_SUERTE_CASUAL  = 2

FRUSTRACION_PERDER = 5
CONFIANZA_PERDER = 5
EGO_GANAR = 5
CARISMA_GANAR = 5
FRUSTRACION_GANAR = 5


MIN_ENERGIA_BEBESTIBLE = 2
MAX_ENERGIA_BEBESTIBLE = 5


DINERO_SHOW = 50
ENERGIA_SHOW = 5
FRUSTRACION_SHOW = 5